AVINASH_URL = r'C:\Users\ravit\Desktop\Teaching\Raviteja_teaching\Examples\EAMCET_conselling\avinash.json'
BHARATH_URL = r'C:\Users\ravit\Desktop\Teaching\Raviteja_teaching\Examples\EAMCET_conselling\bharath.json'
MAHESH_URL = r'C:\Users\ravit\Desktop\Teaching\Raviteja_teaching\Examples\EAMCET_conselling\mahesh.json'
RAVITEJA_URL = r'C:\Users\ravit\Desktop\Teaching\Raviteja_teaching\Examples\EAMCET_conselling\raviteja.json'
VISHNU_URL = r'C:\Users\ravit\Desktop\Teaching\Raviteja_teaching\Examples\EAMCET_conselling\vishnu.json'
VISWESWAR_URL = r'C:\Users\ravit\Desktop\Teaching\Raviteja_teaching\Examples\EAMCET_conselling\visweswar.json'

PAYMENT_INFO_URL = r'C:\Users\ravit\Desktop\Teaching\Raviteja_teaching\Examples\EAMCET_conselling\info'
FEES_INFO_URL = r'C:\Users\ravit\Desktop\Teaching\Raviteja_teaching\Examples\EAMCET_conselling\college_info.xlsx'
EAMCET_NOTICATION_URL = r'C:\Users\ravit\Desktop\Teaching\Raviteja_teaching\Examples\EAMCET_conselling\EAMCET_Notification'
